package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRegistry DO NOT MODIFY.
 */

import byps.*;

public class BRegistry_Taskapp extends BRegistry { 

	public BRegistry_Taskapp() {
		super(BBinaryModel.MEDIUM);
	}
	
	private static BRegisteredSerializer[] serializers = new BRegisteredSerializer[] {
		new BRegisteredSerializer(195526335, "task.app.BSerializer_195526335"),
		new BRegisteredSerializer(216769899, "task.app.BSerializer_216769899"),
		new BRegisteredSerializer(265418285, "task.app.BSerializer_265418285"),
		new BRegisteredSerializer(280075325, "task.app.BSerializer_280075325"),
		new BRegisteredSerializer(484377997, "task.app.BSerializer_484377997"),
		new BRegisteredSerializer(700141099, "task.app.BSerializer_700141099"),
		new BRegisteredSerializer(708578592, "task.app.BSerializer_708578592"),
		new BRegisteredSerializer(1182472339, "task.app.BSerializer_1182472339"),
		new BRegisteredSerializer(1218831438, "task.app.BSerializer_1218831438"),
		new BRegisteredSerializer(1221550298, "task.app.BSerializer_1221550298"),
		new BRegisteredSerializer(1252554176, "task.app.BSerializer_1252554176"),
		new BRegisteredSerializer(1498136965, "task.app.BSerializer_1498136965"),
		new BRegisteredSerializer(1660464439, "task.app.BSerializer_1660464439"),
		new BRegisteredSerializer(1708052887, "task.app.BSerializer_1708052887"),
		new BRegisteredSerializer(1766349022, "task.app.BSerializer_1766349022"),
		new BRegisteredSerializer(1845687418, "task.app.BSerializer_1845687418"),
		new BRegisteredSerializer(1984352081, "task.app.BSerializer_1984352081"),
		new BRegisteredSerializer(2083176447, "task.app.BSerializer_2083176447"),
		new BRegisteredSerializer(2101800006, "task.app.BSerializer_2101800006"),
	};
	@Override
	protected BRegisteredSerializer[] getSortedSerializers() {
		return serializers;
	}
}
