package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BRequest_CalculationService_computeSimpleChecksum extends BMethodRequest implements Serializable {

	public java.util.List<java.io.InputStream> streams;
	
	public final static long serialVersionUID = 700141099L;
	
	public int getRemoteId() { return 1984352081; }
	
	public void execute(BRemote __byps__remote, BAsyncResult<Object> __byps__asyncResult) throws Throwable {
		try {
			final CalculationServiceAsync __byps__remoteT = (CalculationServiceAsync)__byps__remote;			
			BAsyncResultSendMethod<Integer> __byps__outerResult = new BAsyncResultSendMethod<Integer>(__byps__asyncResult, new BResult_5());			
			__byps__remoteT.computeSimpleChecksum(streams, __byps__outerResult);
		} catch (Throwable e) {
			__byps__asyncResult.setAsyncResult(null, e);
		}
	}	
	
	public String toString() {
		StringBuilder s = new StringBuilder();
		s.append("[CalculationService.computeSimpleChecksum(");
		s.append(streams);
		s.append(")]");
		return s.toString();
	}
	
}
