package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BRequest_TaskNotify_receiveTasks extends BMethodRequest implements Serializable {

	public java.util.ArrayList<TaskInfo> tasks;
	
	public final static long serialVersionUID = 2130815904L;
	
	public int getRemoteId() { return 265418285; }
	
	public void execute(BRemote __byps__remote, BAsyncResult<Object> __byps__asyncResult) throws Throwable {
		try {
			final TaskNotifyAsync __byps__remoteT = (TaskNotifyAsync)__byps__remote;			
			BAsyncResultSendMethod<Integer> __byps__outerResult = new BAsyncResultSendMethod<Integer>(__byps__asyncResult, new BResult_5());			
			__byps__remoteT.receiveTasks(tasks, __byps__outerResult);
		} catch (Throwable e) {
			__byps__asyncResult.setAsyncResult(null, e);
		}
	}	
	
	public String toString() {
		StringBuilder s = new StringBuilder();
		s.append("[TaskNotify.receiveTasks(");
		s.append(tasks);
		s.append(")]");
		return s.toString();
	}
	
}
