package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BRequest_TaskService_getCalculationService extends BMethodRequest implements Serializable {

	
	public final static long serialVersionUID = 1708052887L;
	
	public int getRemoteId() { return 216769899; }
	
	public void execute(BRemote __byps__remote, BAsyncResult<Object> __byps__asyncResult) throws Throwable {
		try {
			final TaskServiceAsync __byps__remoteT = (TaskServiceAsync)__byps__remote;			
			BAsyncResultSendMethod<CalculationService> __byps__outerResult = new BAsyncResultSendMethod<CalculationService>(__byps__asyncResult, new BResult_1645863102());			
			__byps__remoteT.getCalculationService(__byps__outerResult);
		} catch (Throwable e) {
			__byps__asyncResult.setAsyncResult(null, e);
		}
	}	
	
	public String toString() {
		StringBuilder s = new StringBuilder();
		s.append("[TaskService.getCalculationService(");
		s.append(")]");
		return s.toString();
	}
	
}
