package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BRequest_TaskService_getTaskAttachments extends BMethodRequest implements Serializable {

	public int taskId;
	
	public final static long serialVersionUID = 708578592L;
	
	public int getRemoteId() { return 216769899; }
	
	public void execute(BRemote __byps__remote, BAsyncResult<Object> __byps__asyncResult) throws Throwable {
		try {
			final TaskServiceAsync __byps__remoteT = (TaskServiceAsync)__byps__remote;			
			BAsyncResultSendMethod<java.util.List<java.io.InputStream>> __byps__outerResult = new BAsyncResultSendMethod<java.util.List<java.io.InputStream>>(__byps__asyncResult, new BResult_1218831438());			
			__byps__remoteT.getTaskAttachments(taskId, __byps__outerResult);
		} catch (Throwable e) {
			__byps__asyncResult.setAsyncResult(null, e);
		}
	}	
	
	public String toString() {
		StringBuilder s = new StringBuilder();
		s.append("[TaskService.getTaskAttachments(");
		s.append(taskId);
		s.append(")]");
		return s.toString();
	}
	
}
