package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BRequest_TaskNotify_receiveTask extends BMethodRequest implements Serializable {

	public TaskInfo task;
	
	public final static long serialVersionUID = 484377997L;
	
	public int getRemoteId() { return 265418285; }
	
	public void execute(BRemote __byps__remote, BAsyncResult<Object> __byps__asyncResult) throws Throwable {
		try {
			final TaskNotifyAsync __byps__remoteT = (TaskNotifyAsync)__byps__remote;			
			BAsyncResultSendMethod<Integer> __byps__outerResult = new BAsyncResultSendMethod<Integer>(__byps__asyncResult, new BResult_5());			
			__byps__remoteT.receiveTask(task, __byps__outerResult);
		} catch (Throwable e) {
			__byps__asyncResult.setAsyncResult(null, e);
		}
	}	
	
	public String toString() {
		StringBuilder s = new StringBuilder();
		s.append("[TaskNotify.receiveTask(");
		s.append(task);
		s.append(")]");
		return s.toString();
	}
	
}
