package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_1645863102 extends BMethodResult<CalculationService> implements Serializable {

	
	public final static long serialVersionUID = 1845687418L;
	
}
