package task.app;

/*
 * Serializer for task.app.BRequest_TaskNotify_receiveTasks
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_2130815904 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_2130815904();
	
	public BSerializer_2130815904() {
		super(2130815904);
	}
	
	public BSerializer_2130815904(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BRequest_TaskNotify_receiveTasks obj = (BRequest_TaskNotify_receiveTasks)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bout.writeObj(obj.tasks, false, task.app.BSerializer_475933318.instance);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BRequest_TaskNotify_receiveTasks obj = (BRequest_TaskNotify_receiveTasks)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_TaskNotify_receiveTasks()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.tasks = (java.util.ArrayList<task.app.TaskInfo>)bin.readObj(false, task.app.BSerializer_475933318.instance);
		
		return obj;
	}
	
}
