package task.app;

/*
 * Serializer for task.app.BStub_CalculationService
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStub DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings("all")
public class BSerializer_1984352081 extends BSerializer_16 {
	
	public final static BSerializer instance = new BSerializer_1984352081();
	
	public BSerializer_1984352081() {
		super(1984352081);
	}
	
	@Override
	public BRemote internalCreate(final BTransport transport) throws BException {
		return new BStub_CalculationService(transport);
	}
	
}
