package task.app;

/*
 * Serializer for task.app.BRequest_TaskService_registerCalculationService
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_1221550298 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_1221550298();
	
	public BSerializer_1221550298() {
		super(1221550298);
	}
	
	public BSerializer_1221550298(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BRequest_TaskService_registerCalculationService obj = (BRequest_TaskService_registerCalculationService)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bout.writeObj(obj.calc, false, null);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BRequest_TaskService_registerCalculationService obj = (BRequest_TaskService_registerCalculationService)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_TaskService_registerCalculationService()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.calc = (task.app.CalculationService)bin.readObj(false, null);
		
		return obj;
	}
	
}
