package task.app;

/*
 * Serializer for task.app.BRequest_TaskService_getTaskAttachments
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_708578592 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_708578592();
	
	public BSerializer_708578592() {
		super(708578592);
	}
	
	public BSerializer_708578592(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BRequest_TaskService_getTaskAttachments obj = (BRequest_TaskService_getTaskAttachments)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putInt(obj.taskId);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BRequest_TaskService_getTaskAttachments obj = (BRequest_TaskService_getTaskAttachments)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_TaskService_getTaskAttachments()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.taskId = bbuf.getInt();
		
		return obj;
	}
	
}
