package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteSkeleton DO NOT MODIFY.
 */

import byps.*;

/**
 * This class provides a skeleton implementation of the interface TaskService.
 * Your interface implementation class has to be derived from this skeleton.
 * Either provide an asynchronous or a synchronous function in your subclass.
 * The framework calls only the asynchronous function.
 */
@SuppressWarnings("all")
public class BSkeleton_TaskService extends BSkeleton implements TaskServiceAsync {
	
	public final static long serialVersionUID = 216769899L;
	
	// checkpoint byps.gen.j.PrintContext:365
	public void addTask(TaskInfo task) throws RemoteException {
		throw new BException(BExceptionC.UNSUPPORTED_METHOD, "");
	}
	// checkpoint byps.gen.j.PrintContext:409
	public void addTask(TaskInfo task, final BAsyncResult<Object> asyncResult) {
		try {
			addTask(task);
			asyncResult.setAsyncResult(null, null);
		} catch (Throwable e) {
			asyncResult.setAsyncResult(null, e);
		}
	}
	
	// checkpoint byps.gen.j.PrintContext:365
	public java.util.List<TaskInfo> getTasks() throws RemoteException {
		throw new BException(BExceptionC.UNSUPPORTED_METHOD, "");
	}
	// checkpoint byps.gen.j.PrintContext:409
	public void getTasks(final BAsyncResult<java.util.List<TaskInfo>> asyncResult) {
		try {
			java.util.List<TaskInfo> ret = getTasks();
			asyncResult.setAsyncResult(ret, null);
		} catch (Throwable e) {
			asyncResult.setAsyncResult(null, e);
		}
	}
	
	// checkpoint byps.gen.j.PrintContext:365
	public void registerCalculationService(CalculationService calc) throws RemoteException {
		throw new BException(BExceptionC.UNSUPPORTED_METHOD, "");
	}
	// checkpoint byps.gen.j.PrintContext:409
	public void registerCalculationService(CalculationService calc, final BAsyncResult<Object> asyncResult) {
		try {
			registerCalculationService(calc);
			asyncResult.setAsyncResult(null, null);
		} catch (Throwable e) {
			asyncResult.setAsyncResult(null, e);
		}
	}
	
	// checkpoint byps.gen.j.PrintContext:365
	public CalculationService getCalculationService() throws RemoteException {
		throw new BException(BExceptionC.UNSUPPORTED_METHOD, "");
	}
	// checkpoint byps.gen.j.PrintContext:409
	public void getCalculationService(final BAsyncResult<CalculationService> asyncResult) {
		try {
			CalculationService ret = getCalculationService();
			asyncResult.setAsyncResult(ret, null);
		} catch (Throwable e) {
			asyncResult.setAsyncResult(null, e);
		}
	}
	
	// checkpoint byps.gen.j.PrintContext:365
	public java.util.List<java.io.InputStream> getTaskAttachments(int taskId) throws RemoteException {
		throw new BException(BExceptionC.UNSUPPORTED_METHOD, "");
	}
	// checkpoint byps.gen.j.PrintContext:409
	public void getTaskAttachments(int taskId, final BAsyncResult<java.util.List<java.io.InputStream>> asyncResult) {
		try {
			java.util.List<java.io.InputStream> ret = getTaskAttachments(taskId);
			asyncResult.setAsyncResult(ret, null);
		} catch (Throwable e) {
			asyncResult.setAsyncResult(null, e);
		}
	}
	
	
}
