package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteSkeleton DO NOT MODIFY.
 */

import byps.*;

/**
 * This class provides a skeleton implementation of the interface TaskNotify.
 * Your interface implementation class has to be derived from this skeleton.
 * Either provide an asynchronous or a synchronous function in your subclass.
 * The framework calls only the asynchronous function.
 */
@SuppressWarnings("all")
public class BSkeleton_TaskNotify extends BSkeleton implements TaskNotifyAsync {
	
	public final static long serialVersionUID = 265418285L;
	
	// checkpoint byps.gen.j.PrintContext:365
	public int receiveTask(TaskInfo task) throws RemoteException {
		throw new BException(BExceptionC.UNSUPPORTED_METHOD, "");
	}
	// checkpoint byps.gen.j.PrintContext:409
	public void receiveTask(TaskInfo task, final BAsyncResult<Integer> asyncResult) {
		try {
			int ret = receiveTask(task);
			asyncResult.setAsyncResult(ret, null);
		} catch (Throwable e) {
			asyncResult.setAsyncResult(null, e);
		}
	}
	
	
}
