package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteStub DO NOT MODIFY.
 */

import byps.*;

// checkpoint byps.gen.j.GenRemoteStub:164
public class BStub_CalculationService extends BStub implements CalculationServiceAsync, java.io.Serializable {
	
	// checkpoint byps.gen.j.GenRemoteStub:145
	public final static long serialVersionUID = 1984352081L;
	
	public BStub_CalculationService(final BTransport transport) {
		super(transport);		
	}
	
	// checkpoint byps.gen.j.PrintContext:365
	public int computeSimpleChecksum(java.util.List<java.io.InputStream> streams) throws RemoteException {
		// checkpoint byps.gen.j.GenRemoteStub:46
		final BSyncResult<Integer> asyncResult = new BSyncResult<Integer>();		
		computeSimpleChecksum(streams, asyncResult);
		return asyncResult.getResult();		
	}
	// checkpoint byps.gen.j.PrintContext:409
	public void computeSimpleChecksum(java.util.List<java.io.InputStream> streams, final BAsyncResult<Integer> asyncResult) {
		// checkpoint byps.gen.j.GenRemoteStub:113
		BRequest_CalculationService_computeSimpleChecksum req = new BRequest_CalculationService_computeSimpleChecksum();		
		req.streams = streams;
		transport.sendMethod(req, asyncResult);
	}
	
	
}
