package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteStub DO NOT MODIFY.
 */

import byps.*;

// checkpoint byps.gen.j.GenRemoteStub:164
public class BStub_TaskNotify extends BStub implements TaskNotifyAsync, java.io.Serializable {
	
	// checkpoint byps.gen.j.GenRemoteStub:145
	public final static long serialVersionUID = 265418285L;
	
	public BStub_TaskNotify(final BTransport transport) {
		super(transport);		
	}
	
	// checkpoint byps.gen.j.PrintContext:365
	public int receiveTasks(java.util.ArrayList<TaskInfo> tasks) throws RemoteException {
		// checkpoint byps.gen.j.GenRemoteStub:46
		final BSyncResult<Integer> asyncResult = new BSyncResult<Integer>();		
		receiveTasks(tasks, asyncResult);
		return asyncResult.getResult();		
	}
	// checkpoint byps.gen.j.PrintContext:409
	public void receiveTasks(java.util.ArrayList<TaskInfo> tasks, final BAsyncResult<Integer> asyncResult) {
		// checkpoint byps.gen.j.GenRemoteStub:113
		BRequest_TaskNotify_receiveTasks req = new BRequest_TaskNotify_receiveTasks();		
		req.tasks = tasks;
		transport.sendMethod(req, asyncResult);
	}
	
	
}
