package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteClassAsync DO NOT MODIFY.
 */

import byps.*;

// checkpoint byps.gen.j.GenRemoteClassAsync:68
public interface CalculationServiceAsync extends BRemote, 
	CalculationService {
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public int computeSimpleChecksum(java.util.List<java.io.InputStream> streams) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void computeSimpleChecksum(java.util.List<java.io.InputStream> streams, final BAsyncResult<Integer> asyncResult) ;
	
	
}
