package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteClassAsync DO NOT MODIFY.
 */

import byps.*;

// checkpoint byps.gen.j.GenRemoteClassAsync:68
public interface TaskNotifyAsync extends BRemote, 
	TaskNotify {
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public int receiveTasks(java.util.ArrayList<TaskInfo> tasks) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void receiveTasks(java.util.ArrayList<TaskInfo> tasks, final BAsyncResult<Integer> asyncResult) ;
	
	
}
