package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRegistry DO NOT MODIFY.
 */

import byps.*;

public class JRegistry_Taskapp extends BRegistry { 

	public JRegistry_Taskapp() {
		super(BBinaryModel.JSON);
	}
	
	private static BRegisteredSerializer[] serializers = new BRegisteredSerializer[] {
		new BRegisteredSerializer(195526335, "task.app.JSerializer_195526335"),
		new BRegisteredSerializer(216769899, "task.app.JSerializer_216769899"),
		new BRegisteredSerializer(265418285, "task.app.JSerializer_265418285"),
		new BRegisteredSerializer(280075325, "task.app.JSerializer_280075325"),
		new BRegisteredSerializer(484377997, "task.app.JSerializer_484377997"),
		new BRegisteredSerializer(700141099, "task.app.JSerializer_700141099"),
		new BRegisteredSerializer(708578592, "task.app.JSerializer_708578592"),
		new BRegisteredSerializer(1182472339, "task.app.JSerializer_1182472339"),
		new BRegisteredSerializer(1218831438, "task.app.JSerializer_1218831438"),
		new BRegisteredSerializer(1221550298, "task.app.JSerializer_1221550298"),
		new BRegisteredSerializer(1252554176, "task.app.JSerializer_1252554176"),
		new BRegisteredSerializer(1498136965, "task.app.JSerializer_1498136965"),
		new BRegisteredSerializer(1660464439, "task.app.JSerializer_1660464439"),
		new BRegisteredSerializer(1708052887, "task.app.JSerializer_1708052887"),
		new BRegisteredSerializer(1766349022, "task.app.JSerializer_1766349022"),
		new BRegisteredSerializer(1845687418, "task.app.JSerializer_1845687418"),
		new BRegisteredSerializer(1984352081, "task.app.JSerializer_1984352081"),
		new BRegisteredSerializer(2083176447, "task.app.JSerializer_2083176447"),
		new BRegisteredSerializer(2101800006, "task.app.JSerializer_2101800006"),
	};
	@Override
	protected BRegisteredSerializer[] getSortedSerializers() {
		return serializers;
	}
}
