package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRegistry DO NOT MODIFY.
 */

import byps.*;

public class JRegistry_Taskapp extends BRegistry { 

	public JRegistry_Taskapp() {
		super(BBinaryModel.JSON);
	}
	
	private static BRegisteredSerializer[] serializers = new BRegisteredSerializer[] {
		new BRegisteredSerializer(195526335, "task.app.JSerializer_195526335"),
		new BRegisteredSerializer(216769899, "task.app.JSerializer_216769899"),
		new BRegisteredSerializer(265418285, "task.app.JSerializer_265418285"),
		new BRegisteredSerializer(280075325, "task.app.JSerializer_280075325"),
		new BRegisteredSerializer(475933318, "task.app.JSerializer_475933318"),
		new BRegisteredSerializer(1182472339, "task.app.JSerializer_1182472339"),
		new BRegisteredSerializer(1218831438, "task.app.JSerializer_1218831438"),
		new BRegisteredSerializer(1252554176, "task.app.JSerializer_1252554176"),
		new BRegisteredSerializer(1265487020, "task.app.JSerializer_1265487020"),
		new BRegisteredSerializer(1498136965, "task.app.JSerializer_1498136965"),
		new BRegisteredSerializer(1660464439, "task.app.JSerializer_1660464439"),
		new BRegisteredSerializer(1766349022, "task.app.JSerializer_1766349022"),
		new BRegisteredSerializer(2101800006, "task.app.JSerializer_2101800006"),
		new BRegisteredSerializer(2130815904, "task.app.JSerializer_2130815904"),
	};
	@Override
	protected BRegisteredSerializer[] getSortedSerializers() {
		return serializers;
	}
}
