package task.app;

/*
 * Serializer for task.app.BRequest_CalculationService_computeSimpleChecksum
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_700141099 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_700141099();
	
	public JSerializer_700141099() {
		super(700141099);
	}
	
	public JSerializer_700141099(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_CalculationService_computeSimpleChecksum obj = (BRequest_CalculationService_computeSimpleChecksum)obj1;		
		bout.writeObj("streams",obj.streams, false, task.app.JSerializer_1218831438.instance);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_CalculationService_computeSimpleChecksum obj = (BRequest_CalculationService_computeSimpleChecksum)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_CalculationService_computeSimpleChecksum()));
		
		final BJsonObject js = bin.currentObject;
		obj.streams = (java.util.List<java.io.InputStream>)bin.readObj("streams", false, task.app.JSerializer_1218831438.instance);
		
		return obj;
	}
	
}
