package task.app;

/*
 * Serializer for task.app.BResult_1218831438
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_2083176447 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_2083176447();
	
	public JSerializer_2083176447() {
		super(2083176447);
	}
	
	public JSerializer_2083176447(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BResult_1218831438 obj = (BResult_1218831438)obj1;		
		bout.writeObj("result",obj.result, false, task.app.JSerializer_1218831438.instance);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BResult_1218831438 obj = (BResult_1218831438)(obj1 != null ? obj1 : bin.onObjectCreated(new BResult_1218831438()));
		
		final BJsonObject js = bin.currentObject;
		obj.result = (java.util.List<java.io.InputStream>)bin.readObj("result", false, task.app.JSerializer_1218831438.instance);
		
		return obj;
	}
	
}
