package task.app;

/*
 * Serializer for task.app.TaskInfo
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=false
// isInline=false
// #members=6

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1660464439 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1660464439();
	
	public JSerializer_1660464439() {
		super(1660464439);
	}
	
	public JSerializer_1660464439(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final TaskInfo obj = (TaskInfo)obj1;		
		bbuf.putDate("dueDate", obj.dueDate);
		bbuf.putInt("id", obj.id);
		bbuf.putString("todo", obj.todo);
		bbuf.putString("userName", obj.userName);
		bout.writeObj("attachments",obj.attachments, false, task.app.JSerializer_1218831438.instance);
		bout.writeObj("properties",obj.properties, false, task.app.JSerializer_1252554176.instance);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final TaskInfo obj = (TaskInfo)(obj1 != null ? obj1 : bin.onObjectCreated(new TaskInfo()));
		
		final BJsonObject js = bin.currentObject;
		obj.dueDate = js.getDate("dueDate");
		obj.id = js.getInt("id");
		obj.todo = js.getString("todo");
		obj.userName = js.getString("userName");
		obj.attachments = (java.util.List<java.io.InputStream>)bin.readObj("attachments", false, task.app.JSerializer_1218831438.instance);
		obj.properties = (java.util.HashMap<java.lang.String,java.lang.String>)bin.readObj("properties", false, task.app.JSerializer_1252554176.instance);
		
		return obj;
	}
	
}
