package task.app;

/*
 * Serializer for task.app.BStub_TaskNotify
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStub DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings("all")
public class JSerializer_265418285 extends JSerializer_16 {
	
	public final static BSerializer instance = new JSerializer_265418285();
	
	public JSerializer_265418285() {
		super(265418285);
	}
	
	@Override
	public BRemote internalCreate(final BTransport transport) throws BException {
		return new BStub_TaskNotify(transport);
	}
	
}
