package task.app;

/*
 * Serializer for task.app.BRequest_TaskService_getTaskAttachments
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_708578592 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_708578592();
	
	public JSerializer_708578592() {
		super(708578592);
	}
	
	public JSerializer_708578592(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_TaskService_getTaskAttachments obj = (BRequest_TaskService_getTaskAttachments)obj1;		
		bbuf.putInt("taskId", obj.taskId);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_TaskService_getTaskAttachments obj = (BRequest_TaskService_getTaskAttachments)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_TaskService_getTaskAttachments()));
		
		final BJsonObject js = bin.currentObject;
		obj.taskId = js.getInt("taskId");
		
		return obj;
	}
	
}
