package task.app;

/*
 * Serializer for task.app.BResult_1645863102
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1845687418 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1845687418();
	
	public JSerializer_1845687418() {
		super(1845687418);
	}
	
	public JSerializer_1845687418(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BResult_1645863102 obj = (BResult_1645863102)obj1;		
		bout.writeObj("result",obj.result, false, null);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BResult_1645863102 obj = (BResult_1645863102)(obj1 != null ? obj1 : bin.onObjectCreated(new BResult_1645863102()));
		
		final BJsonObject js = bin.currentObject;
		obj.result = (task.app.CalculationService)bin.readObj("result", false, null);
		
		return obj;
	}
	
}
