package task.app;

/*
 * Serializer for task.app.BRequest_TaskService_getCalculationService
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=0

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1708052887 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1708052887();
	
	public JSerializer_1708052887() {
		super(1708052887);
	}
	
	public JSerializer_1708052887(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_TaskService_getCalculationService obj = (BRequest_TaskService_getCalculationService)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_TaskService_getCalculationService()));
		
		return obj;
	}
	
}
