package task.app;

/*
 * Serializer for task.app.BRequest_TaskNotify_receiveTask
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_484377997 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_484377997();
	
	public JSerializer_484377997() {
		super(484377997);
	}
	
	public JSerializer_484377997(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_TaskNotify_receiveTask obj = (BRequest_TaskNotify_receiveTask)obj1;		
		bout.writeObj("task",obj.task, false, null);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_TaskNotify_receiveTask obj = (BRequest_TaskNotify_receiveTask)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_TaskNotify_receiveTask()));
		
		final BJsonObject js = bin.currentObject;
		obj.task = (task.app.TaskInfo)bin.readObj("task", false, null);
		
		return obj;
	}
	
}
